In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('trade_usa_import_india.csv')

In [3]:
df.head()

,Product code,Product label,United States of America's imports from India,Unnamed: 3,Unnamed: 4,India's exports to world,Unnamed: 6,Unnamed: 7,Unnamed: 8,United States of America's imports from world,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,Value in 2021,Value in 2022,Value in 2023,NaN,Value in 2021,Value in 2022,Value in 2023,NaN,Value in 2021,Value in 2022,Value in 2023
1,'TOTAL,All products,76929738,90992157,87284471,NaN,394813673,452684214,431418488,NaN,2935314152,3375948186,3172533052
2,'71,"Natural or cultured pearls, precious or semi-p...",15993169,16153422,12366317,NaN,38155138,39274606,33418126,NaN,95969683,96960127,89549261
3,'85,Electrical machinery and equipment and parts t...,3637233,6048732,12078019,NaN,18836214,26573154,32315542,NaN,415442291,477145907,463363545
4,'30,Pharmaceutical products,9107235,9082284,10971299,NaN,19460516,19752792,21295003,NaN,149410420,164993417,177848476

In [11]:
df = df.iloc[:, [0, 1, 2]]
df.drop(index=0)
df.head()

KeyError: '[0] not found in axis'